# Generated by Django 5.2 on 2025-12-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='employee_group',
            field=models.CharField(blank=True, help_text='Группа для организации сотрудников', max_length=100, null=True, verbose_name='Группа сотрудников'),
        ),
    ]