# Generated by Django 5.2.8 on 2025-12-23 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_employee_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Название группы сотрудников"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
            ],
            options={
                "verbose_name": "Группа сотрудников",
                "verbose_name_plural": "Группы сотрудников",
            },
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="employee_group",
        ),
        migrations.AddField(
            model_name="customuser",
            name="employee_groups",
            field=models.ManyToManyField(
                blank=True, to="users.employeegroup", verbose_name="Группы сотрудников"
            ),
        ),
    ]
