# Generated by Django 5.2.8 on 2025-12-04 14:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Клиент"
            ),
        ),
        migrations.AddIndex(
            model_name="client",
            index=models.Index(fields=["name"], name="clients_cli_name_5ab7bc_idx"),
        ),
    ]
