# Generated by Django 6.0 on 2025-12-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_name_client_clients_cli_name_5ab7bc_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='trading_point_address',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Адрес торговой точки'),
        ),
        migrations.AddField(
            model_name='client',
            name='trading_point_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название торговой точки'),
        ),
    ]
