# Generated by Django 5.2.8 on 2026-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0003_client_trading_point_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="stand_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Официальное количество стендов у клиента",
                verbose_name="Количество стендов",
            ),
        ),
    ]
