# Generated by Django 5.2.8 on 2026-03-09 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_stand_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='code_1c',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный код клиента из системы 1С. Используется для синхронизации при изменении наименования контрагента.', max_length=50, null=True, unique=True, verbose_name='Код 1С'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['code_1c'], name='clients_cli_code_1c_5f1b8a_idx'),
        ),
    ]
