# Generated by Django 5.2.8 on 2025-11-29 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reports", "0001_initial"),
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskstatistics",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="tasks.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="taskstatistics",
            unique_together={("task", "client", "employee")},
        ),
    ]
