# Generated by Django 5.2.8 on 2025-11-30 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="TaskStatistics",
        ),
    ]
