# Generated by Django 5.2.8 on 2025-11-29 13:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clients", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question_text",
                    models.CharField(max_length=500, verbose_name="Текст вопроса"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("TEXT", "Текстовое поле"),
                            ("RADIO", "Радиокнопки (одиночный выбор)"),
                            ("CHECKBOX", "Чекбоксы (множественный выбор)"),
                            ("TEXTAREA", "Текстовая область"),
                            ("PHOTO", "Фото"),
                        ],
                        default="TEXT",
                        max_length=20,
                        verbose_name="Тип вопроса",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
            ],
            options={
                "verbose_name": "Вопрос анкеты",
                "verbose_name_plural": "Вопросы анкет",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="PhotoReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=300, verbose_name="Адрес")),
                (
                    "stand_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество стендов"
                    ),
                ),
                (
                    "comment",
                    models.TextField(blank=True, null=True, verbose_name="Комментарий"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фотоотчет",
                "verbose_name_plural": "Фотоотчеты",
            },
        ),
        migrations.CreateModel(
            name="PhotoReportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="photo_reports/%Y/%m/%d/", verbose_name="Фото"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "quality_score",
                    models.FloatField(
                        blank=True,
                        help_text="Оценка качества от 0.0 до 1.0",
                        null=True,
                        verbose_name="Качество фото",
                    ),
                ),
                (
                    "is_accepted",
                    models.BooleanField(default=False, verbose_name="Принято"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="tasks.photoreport",
                        verbose_name="Отчет",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото для отчета",
                "verbose_name_plural": "Фото для отчетов",
            },
        ),
        migrations.CreateModel(
            name="SurveyQuestionChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "choice_text",
                    models.CharField(max_length=200, verbose_name="Текст варианта"),
                ),
                (
                    "is_correct",
                    models.BooleanField(default=False, verbose_name="Правильный ответ"),
                ),
                (
                    "order",
                    models.PositiveIntegerField(default=0, verbose_name="Порядок"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="choices",
                        to="tasks.surveyquestion",
                        verbose_name="Вопрос",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вариант ответа",
                "verbose_name_plural": "Варианты ответов",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SurveyAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text_answer",
                    models.TextField(
                        blank=True, null=True, verbose_name="Текстовый ответ"
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="survey_photos/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Фото",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="answers",
                        to="tasks.surveyquestion",
                        verbose_name="Вопрос",
                    ),
                ),
                (
                    "selected_choices",
                    models.ManyToManyField(
                        blank=True,
                        to="tasks.surveyquestionchoice",
                        verbose_name="Выбранные варианты",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ответ на вопрос",
                "verbose_name_plural": "Ответы на вопросы",
            },
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="Название задачи"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Описание"),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("SURVEY", "Анкета"),
                            ("EQUIPMENT_PHOTO", "Фотоотчет по оборудованию"),
                            ("SIMPLE_PHOTO", "Фотоотчет простой"),
                        ],
                        max_length=20,
                        verbose_name="Тип задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Черновик"),
                            ("SENT", "Отправлено"),
                            ("REWORK", "На доработку"),
                            ("ON_CHECK", "На проверке"),
                            ("COMPLETED", "Завершена"),
                        ],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активная"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "moderator_comment",
                    models.TextField(
                        blank=True, null=True, verbose_name="Комментарий модератора"
                    ),
                ),
                (
                    "target_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Для анкет: сколько клиентов нужно опросить",
                        verbose_name="Целевое количество ответов",
                    ),
                ),
                (
                    "current_count",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Текущее количество ответов"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"role": "EMPLOYEE"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Назначено сотруднику",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        limit_choices_to={"role": "MODERATOR"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создано модератором",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача",
                "verbose_name_plural": "Задачи",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="surveyquestion",
            name="task",
            field=models.ForeignKey(
                limit_choices_to={"task_type": "SURVEY"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="tasks.task",
                verbose_name="Задача",
            ),
        ),
        migrations.AddField(
            model_name="photoreport",
            name="task",
            field=models.ForeignKey(
                limit_choices_to={"task_type__in": ["EQUIPMENT_PHOTO", "SIMPLE_PHOTO"]},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photo_reports",
                to="tasks.task",
                verbose_name="Задача",
            ),
        ),
        migrations.CreateModel(
            name="SurveyClientAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="Завершено"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Завершено"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        limit_choices_to={"role": "EMPLOYEE"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Сотрудник",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        limit_choices_to={"task_type": "SURVEY"},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Назначение клиента к анкете",
                "verbose_name_plural": "Назначения клиентов к анкетам",
                "unique_together": {("task", "client", "employee")},
            },
        ),
    ]
