# Generated by Django 5.2.8 on 2025-11-29 15:18

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("TEXT_SHORT", "Короткое текстовое поле (20 символов)"),
                    ("TEXT", "Текстовое поле"),
                    ("TEXTAREA", "Текстовая область"),
                    ("RADIO", "Радиокнопки (одиночный выбор)"),
                    ("CHECKBOX", "Чекбоксы (множественный выбор)"),
                    ("SELECT_SINGLE", "Выбор из списка (одиночный выбор)"),
                    ("SELECT_MULTIPLE", "Выбор из списка (множественный выбор)"),
                    ("PHOTO", "Фото"),
                ],
                default="TEXT",
                max_length=20,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.CreateModel(
            name="SurveyPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="survey_photos/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Фото",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="survey_photos",
                        to="tasks.surveyanswer",
                        verbose_name="Ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото ответа",
                "verbose_name_plural": "Фото ответов",
            },
        ),
        migrations.AddField(
            model_name="surveyanswer",
            name="photos",
            field=models.ManyToManyField(
                blank=True, to="tasks.surveyphoto", verbose_name="Фотографии"
            ),
        ),
    ]
