# Generated by Django 5.2.8 on 2025-11-29 15:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_alter_surveyquestion_question_type_surveyphoto_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyanswer",
            options={},
        ),
        migrations.RemoveField(
            model_name="surveyanswer",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="surveyanswer",
            name="photos",
        ),
        migrations.CreateModel(
            name="SurveyAnswerPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        upload_to="survey_answer_photos/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "jpeg", "png"]
                            )
                        ],
                        verbose_name="Фото",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "answer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="tasks.surveyanswer",
                        verbose_name="Ответ",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото ответа",
                "verbose_name_plural": "Фото ответов",
            },
        ),
    ]
