# Generated by Django 5.2.8 on 2025-11-29 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_alter_surveyanswer_options_remove_surveyanswer_photo_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="surveyanswer",
            options={
                "verbose_name": "Ответ на вопрос",
                "verbose_name_plural": "Ответы на вопросы",
            },
        ),
    ]
