# Generated by Django 5.2.8 on 2025-11-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0004_alter_surveyanswer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Текстовое поле"),
                    ("TEXT_SHORT", "Короткое текстовое поле (20 символов)"),
                    ("RADIO", "Радиокнопки (одиночный выбор)"),
                    ("CHECKBOX", "Чекбоксы (множественный выбор)"),
                    ("SELECT_SINGLE", "Выбор из списка (одиночный выбор)"),
                    ("SELECT_MULTIPLE", "Выбор из списка (множественный выбор)"),
                    ("PHOTO", "Фото"),
                ],
                default="TEXT",
                max_length=20,
                verbose_name="Тип вопроса",
            ),
        ),
    ]
