# Generated by Django 5.2.8 on 2025-11-30 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_alter_surveyquestion_question_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskStatistics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "total_responses",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Всего ответов"
                    ),
                ),
                (
                    "unique_clients",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Уникальных клиентов"
                    ),
                ),
                (
                    "completion_rate",
                    models.FloatField(default=0.0, verbose_name="Процент выполнения"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tasks.task",
                        verbose_name="Задача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статистика задачи",
                "verbose_name_plural": "Статистика задач",
                "ordering": ["-created_at"],
            },
        ),
    ]
