# Generated by Django 5.2.8 on 2025-12-02 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0006_taskstatistics"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskstatistics",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task_statistics_tasks",
                to="tasks.task",
            ),
        ),
    ]
