# Generated by Django 5.2.8 on 2025-12-04 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0007_alter_taskstatistics_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="surveyanswerphoto",
            name="photo",
            field=models.ImageField(
                upload_to="survey_answer_photos/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png"]
                    )
                ],
                verbose_name="Фото",
            ),
        ),
    ]
