# Generated by Django 6.0 on 2025-12-12 15:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_client_trading_point_address_and_more'),
        ('tasks', '0008_alter_surveyanswerphoto_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyanswerphoto',
            name='photo',
            field=models.ImageField(max_length=500, upload_to='survey_answer_photos/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])], verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='SurveyAnswerGroupReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='Дата создания группы')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Отмечено как прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client', verbose_name='Клиент')),
                ('read_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='read_survey_groups', to=settings.AUTH_USER_MODEL, verbose_name='Прочитано пользователем')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='Задача')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус прочтения группы ответов',
                'verbose_name_plural': 'Статусы прочтения групп ответов',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'client', 'user', 'date_created')},
            },
        ),
    ]
