# Generated by Django 5.2.8 on 2025-12-30 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0013_task_add_client_and_employee_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="TaskSurveyStatsProxy",
            fields=[],
            options={
                "verbose_name": "Статистика задачи",
                "verbose_name_plural": "Статистики задач",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tasks.task",),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("TEXT", "Текстовое поле"),
                    ("TEXT_SHORT", "Короткое текстовое поле (60 символов)"),
                    ("RADIO", "Радиокнопки (одиночный выбор)"),
                    ("CHECKBOX", "Чекбоксы (множественный выбор)"),
                    ("SELECT_SINGLE", "Выбор из списка (одиночный выбор)"),
                    ("SELECT_MULTIPLE", "Выбор из списка (множественный выбор)"),
                    ("PHOTO", "Фото"),
                ],
                default="TEXT",
                max_length=20,
                verbose_name="Тип вопроса",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("SENT", "Отправлено"),
                    ("REWORK", "На доработку"),
                    ("ON_CHECK", "На проверке"),
                    ("ACCEPTED", "Принято"),
                    ("COMPLETED", "Завершена"),
                ],
                default="DRAFT",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
