# Generated by Django 5.2.8 on 2026-01-23 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0016_remove_task_for_all_clients_alter_task_assigned_to_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="stand_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Количество стендов, указанное при создании задачи",
                verbose_name="Количество стендов по умолчанию",
            ),
        ),
    ]
