# Generated by Django 5.2.8 on 2026-02-11 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0018_add_geolocation_fields_to_photoreportitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Черновик"),
                    ("SENT", "В работе"),
                    ("REWORK", "На доработку"),
                    ("ON_CHECK", "На проверке"),
                    ("ACCEPTED", "Принято"),
                    ("COMPLETED", "Завершена"),
                ],
                default="SENT",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
    ]
