# Generated by Django 5.2.8 on 2026-02-12 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_client_stand_count"),
        ("tasks", "0019_alter_task_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyTask",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата задачи")),
                ("description", models.TextField(verbose_name="Описание задачи")),
                (
                    "result",
                    models.TextField(
                        blank=True,
                        null=True,
                        verbose_name="Результат выполнения задачи",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Активная"),
                            ("completed", "Завершенная"),
                            ("hidden", "Скрытая"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "priority",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        default=3,
                        verbose_name="Приоритет задачи",
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Позиция в списке"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создано"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлено"),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assigned_daily_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель задачи",
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="clients.client",
                        verbose_name="Клиент",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_daily_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель задачи",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задача дня",
                "verbose_name_plural": "Задачи дня",
                "ordering": ["position", "-created_at"],
            },
        ),
    ]
