# Generated by Django 5.2.8 on 2026-03-09 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_client_code_1c_client_clients_cli_code_1c_5f1b8a_idx'),
        ('tasks', '0021_update_dailytask_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='clients.client', verbose_name='Клиент (устаревшее)'),
        ),
    ]
