# Generated by Django 6.0 on 2026-04-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_alter_task_client'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dailytask',
            options={'ordering': ['-date'], 'verbose_name': 'Задача дня', 'verbose_name_plural': 'Задачи дня'},
        ),
    ]
