# Generated by Django 6.0 on 2025-12-13 16:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Содержание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('requires_acknowledgment', models.BooleanField(default=False, verbose_name='Требовать подтверждения прочтения')),
                ('target_audience', models.CharField(choices=[('ALL_EMPLOYEES', 'Все сотрудники'), ('MODERATORS', 'Модераторы'), ('ALL_USERS', 'Все пользователи'), ('CUSTOM', 'Выбранные пользователи')], default='ALL_EMPLOYEES', max_length=20, verbose_name='Целевая аудитория')),
                ('author', models.ForeignKey(limit_choices_to={'role': 'MODERATOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnnouncementRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.announcement', verbose_name='Объявление')),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Получатель объявления',
                'verbose_name_plural': 'Получатели объявлений',
                'unique_together': {('announcement', 'recipient_user')},
            },
        ),
        migrations.AddField(
            model_name='announcement',
            name='recipients',
            field=models.ManyToManyField(blank=True, through='announcements.AnnouncementRecipient', to=settings.AUTH_USER_MODEL, verbose_name='Получатели'),
        ),
        migrations.CreateModel(
            name='AnnouncementReadStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True, verbose_name='Прочитано в')),
                ('acknowledged', models.BooleanField(default=False, verbose_name='Подтверждено')),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_statuses', to='announcements.announcement', verbose_name='Объявление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcement_read_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Статус прочтения объявления',
                'verbose_name_plural': 'Статусы прочтения объявлений',
                'ordering': ['-read_at'],
                'unique_together': {('announcement', 'user')},
            },
        ),
    ]
