# Generated by Django 5.2.8 on 2025-12-21 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0009_alter_surveyanswerphoto_photo_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentPhotoReport",
            fields=[],
            options={
                "verbose_name": "Фотоотчет по оборудованию",
                "verbose_name_plural": "Фотоотчеты по оборудованию",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("tasks.photoreport",),
        ),
        migrations.AddField(
            model_name="photoreport",
            name="equipment_fill",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Плохо"), (2, "Средне"), (3, "Хорошо")],
                help_text="Оценка наполнения оборудования: 1 — Плохо, 2 — Средне, 3 — Хорошо",
                null=True,
                verbose_name="Наполнение оборудования",
            ),
        ),
        migrations.AddField(
            model_name="photoreport",
            name="equipment_location",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Плохо"), (2, "Средне"), (3, "Хорошо")],
                help_text="Оценка расположения оборудования в торговом зале",
                null=True,
                verbose_name="Расположение оборудования в торговой точке",
            ),
        ),
        migrations.AddField(
            model_name="photoreport",
            name="moderated_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Время, когда модератор обработал отчёт",
                null=True,
                verbose_name="Время модерации",
            ),
        ),
        migrations.AddField(
            model_name="photoreport",
            name="moderated_by",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"role": "MODERATOR"},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="moderated_photo_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Модератор",
            ),
        ),
        migrations.AddField(
            model_name="photoreport",
            name="no_foreign_goods",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Плохо"), (2, "Средне"), (3, "Хорошо")],
                help_text="Оценка отсутствия посторонних товаров на оборудовании",
                null=True,
                verbose_name="Отсутствие посторонних товаров",
            ),
        ),
        migrations.AddField(
            model_name="photoreport",
            name="product_display",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "Плохо"), (2, "Средне"), (3, "Хорошо")],
                help_text="Оценка выкладки и оформления торговых материалов",
                null=True,
                verbose_name="Выкладка и оформление товаров",
            ),
        ),
    ]