# Generated by Django 5.2 on 2025-12-21 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_equipmentphotoreport_photoreport_equipment_fill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='for_all_clients',
            field=models.BooleanField(default=False, help_text='Если отмечено, задача будет создана для всех клиентов без выбора конкретного.', verbose_name='Для всех клиентов'),
        ),
    ]