# Generated by Django 5.2 on 2025-12-21 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_task_for_all_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='client_group',
            field=models.CharField(blank=True, help_text='Группа клиентов для назначения задачи', max_length=100, null=True, verbose_name='Группа клиентов'),
        ),
        migrations.AddField(
            model_name='task',
            name='employee_group',
            field=models.CharField(blank=True, help_text='Группа сотрудников для назначения задачи', max_length=100, null=True, verbose_name='Группа сотрудников'),
        ),
    ]